version: '3'
services:
  php:
    build: ./docker/php/
    volumes:
      - ./graphql-server:/var/www/app:cached
    working_dir: /var/www/app

  webserver:
    image: nginx:mainline-alpine
    depends_on:
      - php
    volumes:
      - ./graphql-server:/var/www/app:cached
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
