Mutation:
    type: object
    config:
        fields:
            UpdateUserProfile:
                type: UpdateUserProfilePayload
                resolve: "@=mutation('updateUserProfile', [args['input']['name'], args['input']['picture']])"
                args:
                    input: 'UpdateUserProfileInput!'

